name: Summarize Text

on:
  repository_dispatch:
    types: [summarize]

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run summarizer
      id: run
      run: |
        python src/main.py "${{ github.event.client_payload.text }}"

    - name: Set output
      id: output
      run: |
        echo "::set-output name=summary::$(cat summary.json)"